# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13   # Use the desired PostgreSQL version
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
        ports:
          - 5433:5432   # Map container port 5432 to host port 5433
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20.0'

    - name: Wait for PostgreSQL to be ready
      run: until pg_isready -h localhost -p 5433; do echo "Waiting for postgres..."; sleep 1; done

    - name: Run Tests
      env:
        DB_SOURCE: "postgresql://postgres:secret@localhost:5433/testdb?sslmode=disable"
      run: make test
